# https://docs.codecov.com/docs/codecov-yaml
# https://docs.codecov.com/docs/codecovyml-reference
coverage:
  range: 90...100
  status:
    patch:
      default:
        target: 90%
    project:
      default:
        threshold: 2%
        if_ci_failed: error
      whatwg-datetime:
        threshold: 10%
        if_ci_failed: error
        paths:
          - crates/datetime
      whatwg-infra:
        paths:
          - crates/infra

