name: Security audit
on:
  pull_request:
    paths:
      - '.github/workflows/audit.yml'
      - '**/Cargo.toml'
      - '**/Cargo.lock'
  push:
    branches:
      - main
    paths:
      - '.github/workflows/audit.yml'
      - '**/Cargo.toml'
      - '**/Cargo.lock'
  schedule:
    # Run once a week on Monday at 00:00 (12:00AM or Midnight, UTC)
    # See POSIX cron syntax visualized at https://crontab.guru/#0_0_*_*_1
    # GitHub Docs: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onschedule
    # Cron syntax reference: https://pubs.opengroup.org/onlinepubs/9699919799/utilities/crontab.html#tag_20_25_07
    - cron: '0 0 * * 1'
  workflow_dispatch:

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Check if Cargo.lock file exists
        run: |
          if [ -f "Cargo.lock" ]; then
            echo "cargo_lock_exists=true" >> $GITHUB_ENV
          else
            echo "cargo_lock_exists=false" >> $GITHUB_ENV
          fi
      - name: Generate Cargo.lock if file does not exist
        if: env.cargo_lock_exists == 'false'
        run: cargo generate-lockfile
      - name: Install cargo-audit
        uses: taiki-e/install-action@cargo-audit
      - name: Run cargo-audit
        run: cargo audit
